### ISSUE TITLE
Organize companies list

### ISSUE THREAD

**Issue by alinebastos** [alinebastos/remote#20]
Gostaria muito que alguém organizasse a lista de empresas e portais  com o modelo `[Nome do Link](link)`, e arrumasse a ordem alfabética, caso fosse necessário.

I would love for someone to organize the list of companies and portals with the [Link Name](link) template, and arrange the alphabetical order, if necessary.

**Comment by rayanepimentel** [comment]
Oi Aline, o [Nome do Link] seria o nome da empresa? E em alguns casos tem uma mini descrição, ex:
` Go/Golang jobs, filter on remote`, nesse caso mantem, certo?

**Comment by alinebastos** [comment]
Acho eue não precisa manter a descrição, pois como são portais a pessoa já imagina ue deve filtrar :) 
Ah sim, é o nome da empresa denro dos colchetes :)

**Comment by rayanepimentel** [comment]
Aline, eu excluir alguns que não existia mais. ok?
